[project]
name = "adugalam-backend"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "django>=5.2,<6.0",
    "django-cors-headers>=4.9.0",
    "djangorestframework>=3.17.2",
    "djangorestframework-simplejwt>=5.5.1",
    "djangorestframework-stubs>=3.17.1",
    "gunicorn>=26.0.0",
    "mysqlclient>=2.2.8",
    "pillow>=12.3.0",
    "python-decouple>=3.8",
    "python-dotenv>=1.2.2",
    "razorpay>=2.0.1",
    "requests>=2.34.2",
    "supabase>=2.31.0",
]
