services:
  - type: web
    name: adugalam-backend
    env: docker
    dockerContext: turf_backend
    dockerfilePath: turf_backend/Dockerfile
    envVars:
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_CPK2t5RNjDoM@ep-old-salad-azml2p4e-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
      - key: CLOUDINARY_CLOUD_NAME
        value: "qsqs9nz6"
      - key: CLOUDINARY_API_KEY
        value: "956645933373751"
      - key: CLOUDINARY_API_SECRET
        value: "1WRW1KCwWdOZX0FkddJqkE2U8UI"
      - key: SECRET_KEY
        value: "django-insecure-adugalam-backend-render-secret-key-2026"
