services:
  - type: web
    name: adugalam-backend
    env: python
    rootDir: turf_backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn turf_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: "False"
      - key: DB_ENGINE
        value: django.db.backends.postgresql
